version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: genius_seo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: genius_seo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup

volumes:
  postgres_data:


  